import 'package:flutter/material.dart';

import 'color.dart';
import 'size.dart';
const FontWeight w6 = FontWeight.w600;

final TextStyle txt_10_600 = TextStyle(color: black, fontSize: s10, fontWeight: w6);
final TextStyle txt_20_white_600_CM = TextStyle(color: white, fontSize: s20, fontWeight: w6,fontFamily: 'Commic');
final TextStyle txt_14_black_600_CM = TextStyle(color: black, fontSize: s14, fontWeight: FontWeight.w500,fontFamily: 'Commic');
final TextStyle txt_18_white_600_CM = TextStyle(color: white, fontSize: s18, fontWeight: w6,fontFamily: 'Commic');
final TextStyle txt_18_blue_600_CM = TextStyle(color: blue, fontSize: s18, fontFamily: 'Commic');
final TextStyle txt_20_white = TextStyle(color: white, fontSize: s20,);
final TextStyle txt_16_white = TextStyle(color: white, fontSize: s16,);
final TextStyle txt_16_black = TextStyle(color: black, fontSize: s16,);
final TextStyle txt_18_white = TextStyle(color: white, fontSize: s18,);
final TextStyle txt_14_white_600_undr = TextStyle(color: white, fontSize: s14, decoration: TextDecoration.underline);
final TextStyle txt_14_white_600 = TextStyle(color: white, fontSize: s14);
final TextStyle txt_13_white_600_undr = TextStyle(color: white, fontSize: s13, decoration: TextDecoration.underline);
final TextStyle txt_15_white_600_undr = TextStyle(color: white, fontSize: s15, decoration: TextDecoration.underline);
final TextStyle txt_15_blue_600_undr = TextStyle(color: blue, fontSize: s15,fontWeight: w6, decoration: TextDecoration.underline);
final TextStyle txt_14_blue_600 = TextStyle(color: blue, fontSize: s14,fontWeight: w6);
final TextStyle txt_16_blue_600 = TextStyle(color: blue, fontSize: s16,fontWeight: w6);
final TextStyle txt_16_blue = TextStyle(color: blue, fontSize: s16,);
final TextStyle txt_14_black_600 = TextStyle(color: black, fontSize: s14,fontWeight: w6);
final TextStyle txt_16_black_600 = TextStyle(color: black, fontSize: s16,fontWeight: w6);
final TextStyle txt_12_blue_600 = TextStyle(color: blue, fontSize: s12,fontWeight: w6);
final TextStyle txt_12_black_600 = TextStyle(color: black, fontSize: s12,fontWeight: w6);
final TextStyle txt_13_blue_600_undr = TextStyle(color: blue, fontSize: s13,fontWeight: w6, decoration: TextDecoration.underline);
final TextStyle txt_13_blue_600 = TextStyle(color: blue, fontSize: s13,fontWeight: w6,);
final TextStyle txt_11_blue_600 = TextStyle(color: blue, fontSize: s11,fontWeight: w6,);
final TextStyle txt_10_white= TextStyle(color: white, fontSize: s10);
final TextStyle txt_14_white= TextStyle(color: white, fontSize: s14);
final TextStyle txt_13_white = TextStyle(color: white, fontSize: s13,);
final TextStyle txt_15_white = TextStyle(color: white, fontSize: s15,);
final TextStyle txt_14_hint = TextStyle(color: grey, fontSize: s14,);
final TextStyle txt_14_black = TextStyle(color: black, fontSize: s14,);
final TextStyle txt_14_black_500 = TextStyle(color: black, fontSize: s14,fontWeight: FontWeight.w600);
final TextStyle txt_12_black_500 = TextStyle(color: black, fontSize: s12,fontWeight: FontWeight.w500);
final TextStyle txt_10_grey_500 = TextStyle(color: grey, fontSize: s10,fontWeight: FontWeight.w500);
final TextStyle txt_12_black = TextStyle(color: black, fontSize: s12);
final TextStyle txt_12_grey100 = TextStyle(color: grey100.withOpacity(0.8), fontSize: s12);
final TextStyle txt_10_black = TextStyle(color: black, fontSize: s10);
final TextStyle txt_10_grey = TextStyle(color: grey, fontSize: s10);
final TextStyle txt_green = TextStyle(color: green, fontSize: s14, fontWeight: FontWeight.w700);
final TextStyle txt_12_green = TextStyle(color: green, fontSize: s12, fontWeight: FontWeight.w700);